# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Services\Telegram\WorldOfDiaries\Command\HelpCommand:
        arguments:

    App\Services\Telegram\WorldOfDiaries\Command\StartCommand:
        arguments:

    App\Services\Telegram\Logger\LoggerCommandContainer:
        arguments:

    App\Services\Telegram\WorldOfDiaries\WoDCommandContainer:
        arguments:
            - '@App\Services\Telegram\WorldOfDiaries\Command\HelpCommand'
            - '@App\Services\Telegram\WorldOfDiaries\Command\StartCommand'

    App\Services\Telegram\Logger\LoggerTelegramBot:
        arguments:
            - '@Borsaco\TelegramBotApiBundle\Service\Bot'
            - '%env(resolve:TELEGRAM_DEBUG_USER_DEV)%'
            - '@App\Services\Telegram\Logger\LoggerCommandContainer'

    App\Services\Telegram\WorldOfDiaries\WorldOfDiariesBot:
        arguments:
            - '@Borsaco\TelegramBotApiBundle\Service\Bot'
            - '@App\Services\Telegram\WorldOfDiaries\WoDCommandContainer'

    App\Services\Telegram\Logger\TelegramLogger:
        arguments:
            - '@App\Services\Telegram\Logger\LoggerTelegramBot'

    App\Controller\TelegramWebhookController:
        arguments:
            - '@App\Services\Telegram\Logger\TelegramLogger'

    App\EventListener\ExceptionListener:
        arguments:
            - '@twig'
            - '@App\Services\Telegram\Logger\TelegramLogger'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }